#!/usr/bin/env php
<?php
require __DIR__.'/../vendor/autoload.php';

use Application\Command\ProjectInitCommand;
use Symfony\Component\Console\Application;

$application = new Application('echo', '1.0.0');

$application->addCommands([
    new ProjectInitCommand(),
]);

$application->run();